# Generated by Django 3.0.8 on 2020-07-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
        ('salas', '0001_initial'),
        ('cadeiras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadeiras.Cadeira')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.Docente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.Sala')),
            ],
        ),
    ]
