# Generated by Django 3.0.8 on 2020-07-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='name',
        ),
    ]
